version: '3.7'
services:
  postgres:
    image: postgres:11
    environment:
       - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
       - POSTGRES_USER=${DATABASE_USER}
    volumes:
       - ./postgres:/var/lib/postgresql/data
    ports:
       - "5432:5432"
    logging:
      options:
        max-size: 50m